CREATE TABLE IF NOT EXISTS PRICES (
    PRICES_LIST BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID bigint(20) NOT NULL,
    CURRENCY VARCHAR(4) NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    PRIORITY INTEGER(10) NOT NULL,
    PRODUCT_ID BIGINT(20) NOT NULL
);